from pygame import image, transform, font, display, mixer, joystick, draw, QUIT, event, time
from os.path import join
from sys import exit
font.init()
mixer.init()
joystick.init()
screen = display.set_mode((1280, 720))
display.set_caption("Cactus Climber")
joysticks = [joystick.Joystick(x) for x in range(joystick.get_count())]
large_font = font.SysFont('comicsans', 80)
medium_font = font.SysFont('comicsans', 40)
small_font = font.SysFont('comicsans', 20)
font = font.Font(None, 120)
screen.fill((0,0,0))
BAR_WIDTH = 400
BAR_HEIGHT = 20
BAR_X = screen.get_width() // 2 - BAR_WIDTH // 2
BAR_Y = screen.get_height() // 2 + 100
BAR_COLOR = (204, 102, 0)
BAR_BG_COLOR = (50, 50, 50)  # Dark gray background
def show_loading(progress_percent):
    run = True
    clock = time.Clock()
    while run:
        clock.tick(15)
        for e in event.get():
            if e.type == QUIT:
                exit()
        screen.fill((0, 0, 0))
        text = font.render("Loading Assets...", True, (0, 255, 0))
        screen.blit(text, (screen.get_width() // 2 - text.get_width() // 2, screen.get_height() // 2 - text.get_height() // 2))
        draw.rect(screen, BAR_BG_COLOR, (BAR_X, BAR_Y, BAR_WIDTH, BAR_HEIGHT))
        fill_width = int((progress_percent / 100) * BAR_WIDTH)
        draw.rect(screen, BAR_COLOR, (BAR_X, BAR_Y, fill_width, BAR_HEIGHT))
        draw.rect(screen, (100, 100, 100), (BAR_X, BAR_Y, BAR_WIDTH, BAR_HEIGHT), 2)
        display.flip()
        run = False
bottom_cactus = image.load(join('Images', 'cactus', 'bottom_cactus.png')).convert()
bottom_cactus = transform.scale(bottom_cactus, (100, 1000))
mid_cactus = image.load(join('Images', 'cactus', 'mid_cactus.png')).convert()
mid_cactus = transform.scale(mid_cactus, (100, 1000))
display.set_icon(mid_cactus)
top_cactus = image.load(join('Images', 'cactus', 'top_cactus.png')).convert()
top_cactus = transform.scale(top_cactus, (100, 1000))
show_loading(20)
easy_image = image.load(join('Images', 'difficulty', 'easy.png')).convert()
normal_image = image.load(join('Images', 'difficulty', 'normal.png')).convert()
hard_image = image.load(join('Images', 'difficulty', 'hard.png')).convert()
show_stats_image = image.load(join('Images', 'difficulty', 'show_stats.png')).convert()
hide_stats_image = image.load(join('Images', 'difficulty', 'hide_stats.png')).convert()
begin_player = image.load(join('Images', 'player', 'begin_player.png')).convert_alpha()
begin_player = transform.scale(begin_player, (100, 200))
fireball_image = image.load(join('Images', 'obstacles', 'fireball.png')).convert_alpha()
bird_image = image.load(join('Images', 'obstacles', 'bird.png')).convert_alpha()
show_loading(30)
back_image = image.load(join('Images', 'ui', 'back.png')).convert()
checked_off_image = image.load(join('Images', 'ui', 'checked_off.png')).convert()
checked_image = image.load(join('Images', 'ui', 'checked.png')).convert()
credits_image = image.load(join('Images', 'ui', 'credits.png')).convert()
music_image = image.load(join('Images', 'ui', 'music.png')).convert()
options_image = image.load(join('Images', 'ui', 'options.png')).convert()
play_image = image.load(join('Images', 'ui', 'play.png')).convert()
quit_image = image.load(join('Images', 'ui', 'quit.png')).convert()
sfx_image = image.load(join('Images', 'ui', 'sfx.png')).convert()
controller_vibration_image = image.load(join('Images', 'ui', 'controller_vibration.png')).convert()
shop_image = image.load(join('Images', 'ui', 'shop.png')).convert()
reset_image = image.load(join('Images', 'ui', 'reset.png')).convert()
show_loading(40)
achievements_image = image.load(join('Images', 'ui', 'achievements.png')).convert()
first_steps_image = image.load(join('Images', 'achievements', 'first_steps.png')).convert()
climb_the_top_image = image.load(join('Images', 'achievements', 'climb_the_top.png')).convert()
cactus_climber_image = image.load(join('Images', 'achievements', 'cactus_climber.png')).convert()
catch_on_fire_image = image.load(join('Images', 'achievements', 'catch_on_fire.png')).convert()
climb_image = image.load(join('Images', 'achievements', 'climb.png')).convert()
dont_catch_on_fire_image = image.load(join('Images', 'achievements', 'dont_catch_on_fire.png')).convert()
dont_get_hit_image = image.load(join('Images', 'achievements', 'dont_get_hit.png')).convert()
expert_image = image.load(join('Images', 'achievements', 'expert.png')).convert()
get_hit_image = image.load(join('Images', 'achievements', 'get_hit.png')).convert()
the_true_cactus_climber_image = image.load(join('Images', 'achievements', 'the_true_cactus_climber.png')).convert()
hat_collector_image = image.load(join('Images', 'achievements', 'hat_collector.png')).convert()
select_box_image = image.load(join('Images', 'ui', 'select_box.png')).convert_alpha()
textbox_image = image.load(join('Images', 'ui', 'TextBox.png')).convert()
yes_image = image.load(join('Images', 'ui', 'yes.png')).convert()
no_image = image.load(join('Images', 'ui', 'no.png')).convert()
show_loading(50)
begin_1_image = image.load(join('Videos', 'begin', '01.jpg')).convert()
begin_2_image = image.load(join('Videos', 'begin', '02.jpg')).convert()
begin_3_image = image.load(join('Videos', 'begin', '03.jpg')).convert()
begin_4_image = image.load(join('Videos', 'begin', '04.jpg')).convert()
begin_5_image = image.load(join('Videos', 'begin', '05.jpg')).convert()
begin_6_image = image.load(join('Videos', 'begin', '06.jpg')).convert()
begin_7_image = image.load(join('Videos', 'begin', '07.jpg')).convert()
begin_8_image = image.load(join('Videos', 'begin', '08.jpg')).convert()
begin_9_image = image.load(join('Videos', 'begin', '09.jpg')).convert()
begin_10_image = image.load(join('Videos', 'begin', '10.jpg')).convert()
show_loading(60)
birddeath_1_image = image.load(join('Videos', 'birddeath', '01.jpg')).convert()
birddeath_2_image = image.load(join('Videos', 'birddeath', '02.jpg')).convert()
birddeath_3_image = image.load(join('Videos', 'birddeath', '03.jpg')).convert()
birddeath_4_image = image.load(join('Videos', 'birddeath', '04.jpg')).convert()
birddeath_5_image = image.load(join('Videos', 'birddeath', '05.jpg')).convert()
birddeath_6_image = image.load(join('Videos', 'birddeath', '06.jpg')).convert()
birddeath_7_image = image.load(join('Videos', 'birddeath', '07.jpg')).convert()
birddeath_8_image = image.load(join('Videos', 'birddeath', '08.jpg')).convert()
birddeath_9_image = image.load(join('Videos', 'birddeath', '09.jpg')).convert()
birddeath_10_image = image.load(join('Videos', 'birddeath', '10.jpg')).convert()
birddeath_11_image = image.load(join('Videos', 'birddeath', '11.jpg')).convert()
show_loading(70)
end_1_image = image.load(join('Videos', 'end', '01.jpg')).convert()
end_2_image = image.load(join('Videos', 'end', '02.jpg')).convert()
end_3_image = image.load(join('Videos', 'end', '03.jpg')).convert()
end_4_image = image.load(join('Videos', 'end', '04.jpg')).convert()
end_5_image = image.load(join('Videos', 'end', '05.jpg')).convert()
end_6_image = image.load(join('Videos', 'end', '06.jpg')).convert()
end_7_image = image.load(join('Videos', 'end', '07.jpg')).convert()
end_8_image = image.load(join('Videos', 'end', '08.jpg')).convert()
end_9_image = image.load(join('Videos', 'end', '09.jpg')).convert()
end_10_image = image.load(join('Videos', 'end', '10.jpg')).convert()
end_11_image = image.load(join('Videos', 'end', '11.jpg')).convert()
end_12_image = image.load(join('Videos', 'end', '12.jpg')).convert()
end_13_image = image.load(join('Videos', 'end', '13.jpg')).convert()
end_14_image = image.load(join('Videos', 'end', '14.jpg')).convert()
end_15_image = image.load(join('Videos', 'end', '15.jpg')).convert()
end_16_image = image.load(join('Videos', 'end', '16.jpg')).convert()
end_17_image = image.load(join('Videos', 'end', '17.jpg')).convert()
end_18_image = image.load(join('Videos', 'end', '18.jpg')).convert()
end_19_image = image.load(join('Videos', 'end', '19.jpg')).convert()
show_loading(75)
fireballdeath_1_image = image.load(join('Videos', 'fireballdeath', '01.jpg')).convert()
fireballdeath_2_image = image.load(join('Videos', 'fireballdeath', '02.jpg')).convert()
fireballdeath_3_image = image.load(join('Videos', 'fireballdeath', '03.jpg')).convert()
fireballdeath_4_image = image.load(join('Videos', 'fireballdeath', '04.jpg')).convert()
fireballdeath_5_image = image.load(join('Videos', 'fireballdeath', '05.jpg')).convert()
fireballdeath_6_image = image.load(join('Videos', 'fireballdeath', '06.jpg')).convert()
fireballdeath_7_image = image.load(join('Videos', 'fireballdeath', '07.jpg')).convert()
fireballdeath_8_image = image.load(join('Videos', 'fireballdeath', '08.jpg')).convert()
fireballdeath_9_image = image.load(join('Videos', 'fireballdeath', '09.jpg')).convert()
fireballdeath_10_image = image.load(join('Videos', 'fireballdeath', '10.jpg')).convert()
fireballdeath_11_image = image.load(join('Videos', 'fireballdeath', '11.jpg')).convert()
fireballdeath_12_image = image.load(join('Videos', 'fireballdeath', '12.jpg')).convert()
show_loading(80)
red_cap_image = image.load(join('Images', 'shop', 'red_cap.png')).convert_alpha()
thinking_hat_image = image.load(join('Images', 'shop', 'thinking_hat.png')).convert_alpha()
top_hat_image = image.load(join('Images', 'shop', 'top_hat.png')).convert_alpha()
cowboy_hat_image = image.load(join('Images', 'shop', 'cowboy_hat.png')).convert_alpha()
king_hat_image = image.load(join('Images', 'shop', 'king_hat.png')).convert_alpha()
mexican_hat_image = image.load(join('Images', 'shop', 'mexican_hat.png')).convert_alpha()
witch_hat_image = image.load(join('Images', 'shop', 'witch_hat.png')).convert_alpha()
party_hat_image = image.load(join('Images', 'shop', 'party_hat.png')).convert_alpha()
money_image = image.load(join('Images', 'shop', 'money.png')).convert()
equip_image = image.load(join('Images', 'shop', 'equip.png')).convert()
unequip_image = image.load(join('Images', 'shop', 'unequip.png')).convert()
buy_image = image.load(join('Images', 'shop', 'buy.png')).convert()
credits_bg_image = image.load(join('Images', 'credits', 'credits_bg.png')).convert()
show_loading(85)
maintheme = mixer.Sound(join('Music', 'maintheme.mp3'))
dodgemusic = mixer.Sound(join('Music', 'dodge!.mp3'))
firesound = mixer.Sound(join('Music', 'Sounds', 'fire.mp3'))
birdsound = mixer.Sound(join('Music', 'Sounds', 'bird.mp3')) 
buy_sound = mixer.Sound(join('Music', 'Sounds', 'buy.mp3'))
equipped_sound = mixer.Sound(join('Music', 'Sounds', 'equipped.mp3'))
denied_sound = mixer.Sound(join('Music', 'Sounds', 'denied.mp3'))
bg = image.load(join('Images', 'bg.png')).convert_alpha()
show_loading(100)